
# Description:

This dataset, obtained from vgchartz.com, provides a valuable resource for exploring the dynamics between gaming platforms and genres in the top 100 global video games. It enables us to analyze the platforms that are influencing worldwide sales, identify the most prosperous genres in various global regions, and track the evolving trends in both platform preference and genre popularity over time. 



# Goal:

Our goal  from studying this dataset is to utilize classification and clustering techniques on the input data to make predictions about the popularity of upcoming games.




# Attributes discerption:

this dataset has 11 attributes and 16599 objects.

Rank: Ranking of the game based on global sales. 
Name: Name of the game. 
Platform: Platform the game was released on. 
Year: Year the game was released. 
Genre: Genre of the game.
Publisher: Publisher of the game. 
NA_Sales: Sales of the game in North America. 
EU_Sales: Sales of the game in Europe. 
JP_Sales: Sales of the game in Japan. 
Other_Sales: Sales of the game in other regions. 
Global_Sales: Total sales of the game worldwide.


# Class label:
Our class label is “Popular”: it predicts whether a game will sell 1000000 or more globally (regression).


# import dataset
dataset=read.csv("vgsales.csv")

# libraries
library(outliers) 
library(dplyr)
library(Hmisc)
library(ggplot2)
library(cowplot)
library(mlbench)
library(caret)
library(faux)
library(DataExplorer)
library(randomForest)
options(max.print=9999999)

# dataset info
dim(dataset)
names(dataset)

# dataset structure
str(dataset)

# sample of raw dataset(first 10 rows)
head(dataset, 10)

# sample of raw dataset(last 10 rows)
tail(dataset, 10)

# summary of dataset
summary(dataset)

# variance of numeric data
var(dataset$NA_Sales)
var(dataset$EU_Sales)
var(dataset$JP_Sales)
var(dataset$Other_Sales)
var(dataset$Global_Sales)

# Encoding categorical data (Genre)
dataset$Genre=factor(dataset$Genre,levels=c("Action","Adventure","Fighting","Platform","Puzzle","Racing","Role-Playing","Shooter","Simulation","Sports","Strategy","Misc"),labels=c(1,2,3,4,5,6,7,8,9,10,11,12))

# platform pie chart

dataset2 <- dataset %>% sample_n(50)
dataset2$Platform %>% table() %>% pie() # plot pie chart without percentages
# add percentages
tab <- dataset2$Platform %>% table()
precentages <- tab %>% prop.table() %>% round(3) * 100 
txt <- paste0(names(tab), '\n', precentages, '%') # text on chart
pie(tab, labels=txt) # plot pie chart


# Popular genres 
dataset$Genre %>% table() %>% barplot() 

# coloring barplot 
tab<-dataset$Genre %>% table() 

precentages<-tab %>% prop.table() %>% round(3)*100 

txt<-paste0(names(tab), '\n',precentages,'%') 

bb <- dataset$Genre %>% table() %>% barplot(axisnames=F,main='Genre',ylab='count',col=c('pink','blue','lightblue','green','lightgreen','red','orange','red','grey','yellow','azure','olivedrab')) 

text(bb,tab/2,labels=txt,cex=1.5) 

# boxlpt for NA_Sales
boxplot(dataset$NA_Sales)

# boxlpt for EU_Sales
boxplot(dataset$EU_Sales)

# boxlpt for JP_Sales
boxplot(dataset$JP_Sales)

# boxlpt for Other_Sales
boxplot(dataset$Other_Sales) 

# boxlpt for Global_Sales
boxplot(dataset$Global_Sales)

# boxPlots for genre and Global_Sales
qplot(data = dataset, x=Global_Sales,y=Genre,fill=I("yellow"),width=0.5 ,geom = "boxplot")

# barplot for year
dataset$Year %>% table() %>% barplot()

# A matrix of sales Scatter plots
pairs(~NA_Sales + EU_Sales + JP_Sales + Other_Sales + Global_Sales, data = dataset,
      main = "Sales Scatterplot")


